/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "RNSmsModuleSpecJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeSmsModuleCxxSpecJSI_getSMSList(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeSmsModuleCxxSpecJSI *>(&turboModule)->getSMSList(
    rt,
    count <= 0 || args[0].isUndefined() ? std::nullopt : std::make_optional(args[0].asNumber()),
    count <= 1 || args[1].isUndefined() ? std::nullopt : std::make_optional(args[1].asNumber()),
    count <= 2 || args[2].isUndefined() ? std::nullopt : std::make_optional(args[2].asObject(rt))
  );
}
static jsi::Value __hostFunction_NativeSmsModuleCxxSpecJSI_startSmsListener(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  static_cast<NativeSmsModuleCxxSpecJSI *>(&turboModule)->startSmsListener(
    rt
  );
  return jsi::Value::undefined();
}
static jsi::Value __hostFunction_NativeSmsModuleCxxSpecJSI_stopSmsListener(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  static_cast<NativeSmsModuleCxxSpecJSI *>(&turboModule)->stopSmsListener(
    rt
  );
  return jsi::Value::undefined();
}
static jsi::Value __hostFunction_NativeSmsModuleCxxSpecJSI_addListener(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  static_cast<NativeSmsModuleCxxSpecJSI *>(&turboModule)->addListener(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt)
  );
  return jsi::Value::undefined();
}
static jsi::Value __hostFunction_NativeSmsModuleCxxSpecJSI_removeListeners(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  static_cast<NativeSmsModuleCxxSpecJSI *>(&turboModule)->removeListeners(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber()
  );
  return jsi::Value::undefined();
}

NativeSmsModuleCxxSpecJSI::NativeSmsModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("SmsModule", jsInvoker) {
  methodMap_["getSMSList"] = MethodMetadata {3, __hostFunction_NativeSmsModuleCxxSpecJSI_getSMSList};
  methodMap_["startSmsListener"] = MethodMetadata {0, __hostFunction_NativeSmsModuleCxxSpecJSI_startSmsListener};
  methodMap_["stopSmsListener"] = MethodMetadata {0, __hostFunction_NativeSmsModuleCxxSpecJSI_stopSmsListener};
  methodMap_["addListener"] = MethodMetadata {1, __hostFunction_NativeSmsModuleCxxSpecJSI_addListener};
  methodMap_["removeListeners"] = MethodMetadata {1, __hostFunction_NativeSmsModuleCxxSpecJSI_removeListeners};
}


} // namespace facebook::react
